### ISSUE TITLE
Not a bug per se, but this client needs to be upgraded to the latest .Net versions (5+)

### ISSUE THREAD

**Issue by amonsees** [apivideo/api.video-csharp-client#126]
### Version

latest

### Environment that reproduces the issue

Install nuget package in a .Net 8 project and can't access the api client.  Took a minute to realize the version of .Net in the nuget package is .Net 4.5.2 where support ended in April 26, 2022.  The project needs to updates to .Net Standard or .Net 5+ to work with the latest version of .Net

### Is it reproducible in the example application?

Yes

### Reproduction steps

Upgrade project to .Net 8

### Expected result

Updates nuget package with support for .Net 5+

### Actual result

Client does run in the latest runtimes

**Comment by olivierapivideo** [comment]
Hi @amonsees 
We've released a new upgraded version. Please feel free to test it and let us know if it fixes your issue.
