### ISSUE TITLE
[Bug]: Unable to use as nuget

### ISSUE THREAD

**Issue by ChoOo7** [apivideo/api.video-csharp-client#131]
### Version

1.4.0

### Environment that reproduces the issue

Create a blank console project on visual studio, targetting .net5
Install nugets like doc recommand

-> error

### Is it reproducible in the example application?

Yes

### Reproduction steps

Cs proj : 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ApiVideo" Version="1.4.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JsonSubTypes" Version="2.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="111.4.0" />
  </ItemGroup>

</Project>
```

Program.cs
```
using System;
using ApiVideo.Api;
using ApiVideo.Client;
using ApiVideo.Model;

namespace testapivideo
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var apiKey = "YOUR_API_KEY";

            var apiVideoClient = new ApiVideoClient(apiKey);

        }
    }
}
```

### Expected result

Compile fine

### Actual result

Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur (active)	CS0246	Le nom de type ou d'espace de noms 'ApiVideo' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?)	testapivideo	C:\tmp\testapivideo\testapivideo\Program.cs	2

**Comment by ChoOo7** [comment]
@olivierapivideo reproduisez vous mon souci ? Je m'y prend mal ?
J'ai tenté de regarder le contenu du packagge nuget avec un nuget explorer mais on ne voit trop rien...
Par avance, merci

**Comment by olivierapivideo** [comment]
Bonjour @ChoOo7 
Nous regardons à votre problème au plus tôt (dans la semaine).

**Comment by olivierapivideo** [comment]
Bonjour @ChoOo7 
Nous venons de publier une version 1.5.0 qui corrige ce problème. 
Merci pour votre retour et désolé pour la gène occasionnée !
